set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g focus-events on
set -g mouse on
set -g history-limit 100000

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-style "fg=#b8a7b9,bg=#181825"
set -g status-left-length 60
set -g status-right-length 100

setw -g window-status-format " #I #W "
setw -g window-status-style "fg=#7f7a8e,bg=#181825"
setw -g window-status-current-format " #I #W "
setw -g window-status-current-style "fg=#181825,bg=#a8a0cc"
setw -g window-status-bell-style "fg=#181825,bg=#f4777f"

set -g pane-border-style "fg=#3b3f54"
set -g pane-active-border-style "fg=#a8a0cc"

set -g status-left "#[fg=#181825,bg=#d7a4b8,bold] #S #[fg=#d7a4b8,bg=#181825]"
set -g status-right "#[fg=#8a8a8a,bg=#181825] %Y-%m-%d %H:%M #[fg=#a8a0cc,bg=#181825] | #h "

set -g message-style "fg=#181825,bg=#a8a0cc"
set -g mode-style "fg=#181825,bg=#a8a0cc"

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
