#!/usr/bin/env bash
#
# macstrap installer. Idempotent and safe to re-run.
#
# Modes (MODE=...):
#   minimal      shell + git + chezmoi + mise + CLI core only (no GUI apps)
#   default      recommended stack: core + default apps            (the default)
#   interactive  pick your apps from a menu (installs gum; needs a terminal)
#   headless     core only, no GUI apps (safe for CI / remote Macs)
#   doctor       run health checks only; change nothing
#
# App selection (APPS=...), overrides the mode default:
#   0            none
#   default      everything tagged "default" in brew/apps.catalog
#   interactive  choose from the catalog
#   a,b,c        an explicit comma-separated list of cask tokens
#
# Other env:
#   PROFILE=personal|work   preset the chezmoi profile (else prompted at init)
#   DRY_RUN=1               preview the plan; make no changes
#
# Examples:
#   bash scripts/bootstrap.sh
#   MODE=minimal bash scripts/bootstrap.sh
#   DRY_RUN=1 bash scripts/bootstrap.sh
#   PROFILE=work APPS=cursor,orbstack,tableplus bash scripts/bootstrap.sh
#
set -euo pipefail

REPO_SLUG="${REPO_SLUG:-XavierAgostino/macstrap}"
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/Developer/workspaces/macstrap}"
REPO_URL="${REPO_URL:-https://github.com/$REPO_SLUG.git}"
MODE="${MODE:-default}"
PROFILE="${PROFILE:-}"
APPS="${APPS:-}"
DRY_RUN="${DRY_RUN:-0}"

CATALOG="$DOTFILES_DIR/brew/apps.catalog"
WARNINGS=()
SELECTED_APPS=""

# --- output helpers (colored text labels, no emoji) ---
b=$'\033[1;34m'; g=$'\033[32m'; y=$'\033[33m'; r=$'\033[31m'; x=$'\033[0m'
log()  { printf '\n%s==>%s %s\n' "$b" "$x" "$*"; }
ok()   { printf '  %sok%s   %s\n'   "$g" "$x" "$*"; }
warn() { printf '  %swarn%s %s\n'   "$y" "$x" "$*"; }
die()  { printf '  %sfail%s %s\n'   "$r" "$x" "$*"; exit 1; }

# run a REQUIRED step; abort on failure
run_required() { local d="$1"; shift; if "$@"; then ok "$d"; else die "$d"; fi; }
# run an OPTIONAL step; record a warning and continue on failure
run_optional() { local d="$1"; shift; if "$@"; then ok "$d"; else warn "$d (continued)"; WARNINGS+=("$d"); fi; }

# link the `macstrap` CLI onto PATH (~/.local/bin is added to PATH in .zprofile)
link_cli() { mkdir -p "$HOME/.local/bin" && ln -sf "$DOTFILES_DIR/bin/macstrap" "$HOME/.local/bin/macstrap"; }

# --- catalog helpers ---
catalog_by_tag()  { awk -F'|' -v t="$1" '!/^#/ && NF>=3 { n=split($3,a,","); for(i=1;i<=n;i++) if(a[i]==t) print $1 }' "$CATALOG"; }
catalog_tokens()  { awk -F'|' '!/^#/ && NF>=1 && $1!="" { print $1 }' "$CATALOG"; }

# resolve APPS (respecting MODE default) to a newline list of cask tokens
resolve_apps() {
  local sel="$APPS"
  if [[ -z "$sel" ]]; then
    case "$MODE" in minimal|headless) sel=0 ;; interactive) sel=interactive ;; *) sel=default ;; esac
  fi
  case "$sel" in
    0|none|minimal) : ;;
    default)        catalog_by_tag default ;;
    interactive)    interactive_pick ;;
    *)              printf '%s' "$sel" | tr ',' '\n' | sed '/^[[:space:]]*$/d' ;;
  esac
}

interactive_pick() {
  command -v gum >/dev/null 2>&1 || brew install gum >/dev/null 2>&1 || true
  if command -v gum >/dev/null 2>&1 && [ -t 0 ]; then
    catalog_tokens | gum choose --no-limit --height 20 \
      --header "Select apps to install (space toggles, enter confirms):"
  else
    warn "No interactive terminal; using the default app set." >&2
    catalog_by_tag default
  fi
}

# Resolve the app selection exactly once (interactive mode shows the picker here).
compute_apps() { SELECTED_APPS="$(resolve_apps)"; }
apps_count()   { printf '%s\n' "$SELECTED_APPS" | sed '/^$/d' | grep -c . 2>/dev/null || echo 0; }

install_apps() {
  local count; count="$(apps_count)"
  if [[ "${count:-0}" -eq 0 ]]; then log "Apps: none"; return 0; fi
  local gen="$DOTFILES_DIR/brew/generated"; mkdir -p "$gen"
  { echo "# Generated by macstrap on $(date +%F). Do not edit."
    printf '%s\n' "$SELECTED_APPS" | sed '/^$/d' | sed 's/.*/cask "&"/'; } > "$gen/Brewfile.apps.local"
  run_optional "Installing $count app(s)" brew bundle --file="$gen/Brewfile.apps.local"
}

print_plan() {
  log "DRY RUN, no changes will be made. Planned actions:"
  printf '  %-15s %s\n' "Mode:"          "$MODE"
  printf '  %-15s %s\n' "Homebrew:"      "$(command -v brew >/dev/null 2>&1 && echo installed || echo 'would install')"
  printf '  %-15s %s\n' "Repo:"          "$([[ -d "$DOTFILES_DIR/.git" ]] && echo present || echo "would clone $REPO_SLUG")"
  printf '  %-15s %s\n' "chezmoi:"       "$(command -v chezmoi >/dev/null 2>&1 && echo installed || echo 'would install') -> init + apply"
  printf '  %-15s %s\n' "Runtimes:"      "mise install"
  printf '  %-15s %s\n' "Core packages:" "$(grep -cE '^(brew|cask) ' "$DOTFILES_DIR/brew/Brewfile.core" 2>/dev/null || echo '?') from Brewfile.core"
  printf '  %-15s %s\n' "Apps:"          "$(apps_count) selected"
  printf '  %-15s %s\n' "Profile:"       "${PROFILE:-prompt at init}"
}

# ---------------------------------------------------------------------------
# doctor mode: check only, change nothing
if [[ "$MODE" == "doctor" ]]; then exec bash "$DOTFILES_DIR/scripts/dev-doctor.sh"; fi

# Resolve apps once (interactive mode shows the picker now, before any changes).
compute_apps

# dry run: print the plan and exit before mutating anything
if [[ "$DRY_RUN" == "1" ]]; then print_plan; exit 0; fi

log "macstrap installer (mode: $MODE)"

# 1. Homebrew
command -v brew >/dev/null 2>&1 || \
  run_required "Installing Homebrew" /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
[[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# 2. Clone the repo if missing
[[ -d "$DOTFILES_DIR/.git" ]] || run_required "Cloning $REPO_SLUG" git clone "$REPO_URL" "$DOTFILES_DIR"

# 3. chezmoi + secret-scan hook
command -v chezmoi >/dev/null 2>&1 || run_required "Installing chezmoi" brew install chezmoi
run_optional "Enabling the gitleaks pre-commit hook" git -C "$DOTFILES_DIR" config core.hooksPath scripts/hooks
run_optional "Linking the macstrap CLI (~/.local/bin/macstrap)" link_cli

# 4. chezmoi init + apply
run_required "chezmoi init" chezmoi init --source="$DOTFILES_DIR"
log "Preview (chezmoi diff):"; chezmoi diff || true
run_required "chezmoi apply" chezmoi apply

# 5. Runtimes
command -v mise >/dev/null 2>&1 || run_required "Installing mise" brew install mise
run_optional "Installing runtimes (mise)" mise install

# 6. Homebrew packages: core, then apps, then the active profile
run_required "Installing core packages" brew bundle --file="$DOTFILES_DIR/brew/Brewfile.core"
install_apps
[[ -z "$PROFILE" ]] && PROFILE="$(chezmoi execute-template '{{ .profile }}' 2>/dev/null || true)"
case "$PROFILE" in
  personal) run_optional "Installing personal packages" brew bundle --file="$DOTFILES_DIR/brew/Brewfile.personal" ;;
  work)     run_optional "Installing work packages"     brew bundle --file="$DOTFILES_DIR/brew/Brewfile.work" ;;
esac

# 7. Health check
run_optional "Running dev-doctor" bash "$DOTFILES_DIR/scripts/dev-doctor.sh"

# 8. Summary
if [[ ${#WARNINGS[@]} -eq 0 ]]; then
  log "Bootstrap complete with no warnings."
else
  log "Bootstrap completed with ${#WARNINGS[@]} warning(s):"
  for w in "${WARNINGS[@]}"; do warn "$w"; done
  echo "  Re-check with: bash scripts/dev-doctor.sh"
fi
echo "  Open a new terminal (or run 'exec zsh') to load the shell."
